name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version
          required: false
        - label: I have read the documentation
          required: false

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module is affected?
      options:
        - Authentication & Security (auth, security)
        - Content Management (content, community)
        - Multi-channel Publishing (publish)
        - Governance Module (committee, meeting)
        - Analytics & Dashboard (analytics)
        - Infrastructure (database, CI/CD)
        - Frontend UI
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down, data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened, including error messages
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs
      placeholder: |
        Paste error logs here (check browser console, backend logs, or docker logs)
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      value: |
        - OS: [e.g., macOS 13.0, Ubuntu 22.04, Windows 11]
        - Browser: [e.g., Chrome 120, Firefox 121]
        - Backend Version: [e.g., v1.2.0]
        - Frontend Version: [e.g., v1.2.0]
        - Python Version: [e.g., 3.11.5]
        - Node.js Version: [e.g., 18.17.0]
        - Database: [e.g., PostgreSQL 15.3, SQLite]
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does this happen consistently or intermittently?
        - Are there any workarounds?
        - When did this start happening?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute a fix?
      options:
        - label: I am willing to submit a PR to fix this bug
          required: false
