name: 📝 Documentation
description: Report missing or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear explanation
        - Broken link
        - Typo or grammar error
        - API documentation
        - Code example needed
        - Translation issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation?
      options:
        - README.md
        - docs/requirements/ (Requirements documentation)
        - docs/design/ (Design documentation)
        - docs/api/ (API documentation)
        - docs/plannings/ (Planning documentation)
        - Code comments / docstrings
        - CHANGELOG.md
        - CONTRIBUTING.md
        - Other
    validations:
      required: true

  - type: textarea
    id: file-path
    attributes:
      label: File Path
      description: If known, provide the specific file path
      placeholder: "e.g., docs/api/auth-api.md or backend/app/api/auth.py"

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (copy/paste or link)
      placeholder: |
        Paste the current documentation content or provide a link
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What is wrong or missing?
      placeholder: |
        Clearly describe the issue:
        - What information is missing?
        - What is incorrect or outdated?
        - Why is it confusing?
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: What should the documentation say instead?
      placeholder: |
        Provide your suggested improvement:
        - Corrected text
        - Additional information to include
        - Better examples
        - Clearer structure
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information
      placeholder: |
        - Who is the target audience?
        - Related documentation that needs updating
        - Screenshots if UI-related

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute the fix?
      options:
        - label: I am willing to submit a PR to fix this documentation
          required: false
