name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: false

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module would this feature belong to?
      options:
        - Authentication & Security (auth, security)
        - Content Management (content, community)
        - Multi-channel Publishing (publish)
        - Governance Module (committee, meeting)
        - Analytics & Dashboard (analytics)
        - Infrastructure (database, CI/CD)
        - Frontend UI
        - Cross-cutting (affects multiple modules)
        - New Module
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocking major functionality)
        - High (Important for user experience)
        - Medium (Nice to have, improves usability)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.
        Example: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include:
        - User stories (As a [role], I want [feature] so that [benefit])
        - UI/UX mockups (if applicable)
        - API design (if applicable)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Use case 1: ...
        2. Use case 2: ...
        3. Use case 3: ...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this feature to be considered complete?
      placeholder: |
        - [ ] User can do X
        - [ ] System validates Y
        - [ ] UI displays Z
        - [ ] API endpoint /api/... returns ...

  - type: textarea
    id: design-considerations
    attributes:
      label: Design Considerations
      description: Any design, architecture, or technical considerations?
      placeholder: |
        - Database schema changes needed?
        - Performance implications?
        - Security concerns?
        - Backward compatibility?
        - Third-party integrations?

  - type: dropdown
    id: user-role
    attributes:
      label: User Role
      description: Who is the primary beneficiary of this feature?
      options:
        - Platform Administrator
        - Community Manager
        - Committee Member
        - Content Creator
        - Content Publisher
        - End User (viewer)
        - All Users
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Wireframes
      description: If applicable, add mockups or wireframes
      placeholder: Drag and drop images here, or link to Figma/other design tools

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: |
        - Similar features in other platforms
        - Related documentation or resources
        - Potential blockers or dependencies

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute this feature?
      options:
        - label: I am willing to submit a PR to implement this feature
          required: false
        - label: I am willing to help with design/planning
          required: false
        - label: I am willing to help with testing
          required: false
