"""initial_schema

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-03-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_default_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('owner_ids', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)

    op.create_table('channel_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'channel', name='uq_community_channel')
    )
    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_configs_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_configs_id'), ['id'], unique=False)

    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('meeting_frequency', sa.String(length=50), nullable=True),
    sa.Column('notification_email', sa.String(length=200), nullable=True),
    sa.Column('notification_wechat', sa.String(length=100), nullable=True),
    sa.Column('established_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_committee_community_slug')
    )
    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committees_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committees_id'), ['id'], unique=False)

    op.create_table('community_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('contribution', 'release_note', 'event_summary', name='source_type_enum'), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'reviewing', 'approved', 'published', name='status_enum'), nullable=True),
    sa.Column('work_status', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_scheduled_publish_at'), ['scheduled_publish_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_work_status'), ['work_status'], unique=False)

    op.create_table('ecosystem_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecosystem_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecosystem_projects_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_projects_id'), ['id'], unique=False)

    op.create_table('event_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.Enum('online', 'offline', 'hybrid', name='event_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_templates_community_id'), ['community_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)

    op.create_table('person_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_handle', sa.String(length=100), nullable=True),
    sa.Column('gitcode_handle', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'event_import', 'ecosystem_import', name='person_source_enum'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_profiles_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_profiles_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_profiles_gitcode_handle'), ['gitcode_handle'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_profiles_github_handle'), ['github_handle'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_profiles_id'), ['id'], unique=False)

    op.create_table('wechat_stats_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('daily', 'weekly', 'monthly', 'quarterly', 'semi_annual', 'annual', name='period_type_enum'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('article_category', sa.Enum('release', 'technical', 'activity', name='article_category_enum'), nullable=True),
    sa.Column('total_articles', sa.Integer(), nullable=True),
    sa.Column('total_read_count', sa.Integer(), nullable=True),
    sa.Column('total_read_user_count', sa.Integer(), nullable=True),
    sa.Column('total_like_count', sa.Integer(), nullable=True),
    sa.Column('total_wow_count', sa.Integer(), nullable=True),
    sa.Column('total_share_count', sa.Integer(), nullable=True),
    sa.Column('total_comment_count', sa.Integer(), nullable=True),
    sa.Column('total_favorite_count', sa.Integer(), nullable=True),
    sa.Column('total_forward_count', sa.Integer(), nullable=True),
    sa.Column('total_new_follower_count', sa.Integer(), nullable=True),
    sa.Column('avg_read_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'period_type', 'period_start', 'article_category', name='uq_stats_aggregate')
    )
    with op.batch_alter_table('wechat_stats_aggregates', schema=None) as batch_op:
        batch_op.create_index('ix_aggregate_period', ['community_id', 'period_type', 'period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_stats_aggregates_article_category'), ['article_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_stats_aggregates_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_stats_aggregates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_stats_aggregates_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_stats_aggregates_period_type'), ['period_type'], unique=False)

    op.create_table('campaign_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=300), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_activities_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_activities_person_id'), ['person_id'], unique=False)

    op.create_table('campaign_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('added_by', sa.String(length=50), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_contacts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_contacts_person_id'), ['person_id'], unique=False)

    op.create_table('campaign_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_ids', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_tasks_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_tasks_id'), ['id'], unique=False)

    op.create_table('checklist_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('pre', 'during', 'post', name='checklist_phase_enum'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('responsible_role', sa.String(length=100), nullable=True),
    sa.Column('deadline_offset_days', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['event_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_template_items_template_id'), ['template_id'], unique=False)

    op.create_table('committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('gitcode_id', sa.String(length=100), nullable=True),
    sa.Column('github_id', sa.String(length=100), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('term_start', sa.Date(), nullable=True),
    sa.Column('term_end', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_members_committee_id'), ['committee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_members_person_id'), ['person_id'], unique=False)

    op.create_table('community_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('community_name', sa.String(length=200), nullable=False),
    sa.Column('project_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_roles_person_id'), ['person_id'], unique=False)

    op.create_table('content_assets',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'asset_id')
    )
    op.create_table('content_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_assignees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_assignees_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assignees_user_id'), ['user_id'], unique=False)

    op.create_table('content_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_communities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_communities_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_communities_content_id'), ['content_id'], unique=False)

    op.create_table('design_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_tasks_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_tasks_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('ecosystem_contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('github_handle', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('commit_count_90d', sa.Integer(), nullable=True),
    sa.Column('pr_count_90d', sa.Integer(), nullable=True),
    sa.Column('star_count', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count_90d', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('first_contributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['ecosystem_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecosystem_contributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecosystem_contributors_github_handle'), ['github_handle'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_contributors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_contributors_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_contributors_project_id'), ['project_id'], unique=False)

    op.create_table('ecosystem_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('open_prs', sa.Integer(), nullable=True),
    sa.Column('commits_30d', sa.Integer(), nullable=True),
    sa.Column('pr_merged_30d', sa.Integer(), nullable=True),
    sa.Column('active_contributors_30d', sa.Integer(), nullable=True),
    sa.Column('new_contributors_30d', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['ecosystem_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecosystem_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecosystem_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_snapshots_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_snapshots_snapshot_at'), ['snapshot_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('event_type', sa.Enum('online', 'offline', 'hybrid', name='event_type_enum'), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'ongoing', 'completed', name='event_status_enum'), nullable=True),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('online_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('attendee_count', sa.Integer(), nullable=True),
    sa.Column('online_count', sa.Integer(), nullable=True),
    sa.Column('offline_count', sa.Integer(), nullable=True),
    sa.Column('registration_count', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['event_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_community_id'), ['community_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('online_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('work_status', sa.String(length=50), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_before_hours', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_committee_id'), ['committee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_work_status'), ['work_status'], unique=False)

    op.create_table('publish_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('wechat', 'hugo', 'csdn', 'zhihu', name='pub_channel_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'draft', 'published', 'failed', name='pub_status_enum'), nullable=True),
    sa.Column('platform_article_id', sa.String(length=200), nullable=True),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_records_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_records_id'), ['id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('pre', 'during', 'post', name='checklist_item_phase_enum'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('responsible_role', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'skipped', name='checklist_status_enum'), nullable=True),
    sa.Column('assignee_ids', sa.JSON(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_event_id'), ['event_id'], unique=False)

    op.create_table('content_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_record_id', sa.Integer(), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publish_record_id'], ['publish_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_analytics_id'), ['id'], unique=False)

    op.create_table('event_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('role_at_event', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('manual', 'excel_import', name='attendee_source_enum'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_attendees_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_attendees_person_id'), ['person_id'], unique=False)

    op.create_table('event_communities',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'community_id')
    )
    op.create_table('event_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('assignee_type', sa.Enum('internal', 'external', name='personnel_assignee_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Enum('pending', 'confirmed', 'declined', name='personnel_confirm_enum'), nullable=True),
    sa.Column('time_slot', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_personnel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_personnel_event_id'), ['event_id'], unique=False)

    op.create_table('event_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('task_type', sa.Enum('task', 'milestone', name='task_type_enum'), nullable=True),
    sa.Column('phase', sa.Enum('pre', 'during', 'post', name='task_phase_enum'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'blocked', name='task_status_enum'), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('assignee_ids', sa.JSON(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['event_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_tasks_event_id'), ['event_id'], unique=False)

    op.create_table('feedback_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('raised_by', sa.String(length=200), nullable=True),
    sa.Column('raised_by_person_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='feedback_status_enum'), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_person_id'], ['person_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_items_event_id'), ['event_id'], unique=False)

    op.create_table('meeting_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_assignees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_assignees_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_assignees_user_id'), ['user_id'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'email', name='uq_meeting_participant_email')
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_participants_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_participants_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_reminders', schema=None) as batch_op:
        batch_op.create_index('idx_reminder_scheduled_status', ['scheduled_at', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_reminders_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('wechat_article_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_record_id', sa.Integer(), nullable=False),
    sa.Column('article_category', sa.Enum('release', 'technical', 'activity', name='article_category_enum'), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('read_user_count', sa.Integer(), nullable=True),
    sa.Column('read_original_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('wow_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('forward_count', sa.Integer(), nullable=True),
    sa.Column('new_follower_count', sa.Integer(), nullable=True),
    sa.Column('unfollow_count', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publish_record_id'], ['publish_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publish_record_id', 'stat_date', name='uq_article_stat_date')
    )
    with op.batch_alter_table('wechat_article_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wechat_article_stats_article_category'), ['article_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_article_stats_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_article_stats_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_article_stats_publish_record_id'), ['publish_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_article_stats_stat_date'), ['stat_date'], unique=False)
        batch_op.create_index('ix_wechat_stats_category_date', ['article_category', 'stat_date'], unique=False)
        batch_op.create_index('ix_wechat_stats_community_date', ['community_id', 'stat_date'], unique=False)

    op.create_table('issue_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('github', 'gitcode', 'gitee', name='issue_platform_enum'), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('issue_url', sa.String(length=500), nullable=False),
    sa.Column('issue_type', sa.Enum('issue', 'pr', name='issue_type_enum'), nullable=True),
    sa.Column('issue_status', sa.Enum('open', 'closed', name='issue_status_enum'), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_links_feedback_id'), ['feedback_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_links_feedback_id'))

    op.drop_table('issue_links')
    with op.batch_alter_table('wechat_article_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_wechat_stats_community_date')
        batch_op.drop_index('ix_wechat_stats_category_date')
        batch_op.drop_index(batch_op.f('ix_wechat_article_stats_stat_date'))
        batch_op.drop_index(batch_op.f('ix_wechat_article_stats_publish_record_id'))
        batch_op.drop_index(batch_op.f('ix_wechat_article_stats_id'))
        batch_op.drop_index(batch_op.f('ix_wechat_article_stats_community_id'))
        batch_op.drop_index(batch_op.f('ix_wechat_article_stats_article_category'))

    op.drop_table('wechat_article_stats')
    with op.batch_alter_table('meeting_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_reminders_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_reminders_id'))
        batch_op.drop_index('idx_reminder_scheduled_status')

    op.drop_table('meeting_reminders')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_participants_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_participants_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_participants_email'))

    op.drop_table('meeting_participants')
    with op.batch_alter_table('meeting_assignees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_assignees_user_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_assignees_meeting_id'))

    op.drop_table('meeting_assignees')
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_items_event_id'))

    op.drop_table('feedback_items')
    with op.batch_alter_table('event_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_tasks_event_id'))

    op.drop_table('event_tasks')
    with op.batch_alter_table('event_personnel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_personnel_event_id'))

    op.drop_table('event_personnel')
    op.drop_table('event_communities')
    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_attendees_person_id'))
        batch_op.drop_index(batch_op.f('ix_event_attendees_event_id'))

    op.drop_table('event_attendees')
    with op.batch_alter_table('content_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_analytics_id'))

    op.drop_table('content_analytics')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_event_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('publish_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_records_id'))
        batch_op.drop_index(batch_op.f('ix_publish_records_community_id'))

    op.drop_table('publish_records')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_work_status'))
        batch_op.drop_index(batch_op.f('ix_meetings_status'))
        batch_op.drop_index(batch_op.f('ix_meetings_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_meetings_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_community_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_committee_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_community_id'))

    op.drop_table('events')
    with op.batch_alter_table('ecosystem_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecosystem_snapshots_snapshot_at'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_snapshots_project_id'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_snapshots_id'))

    op.drop_table('ecosystem_snapshots')
    with op.batch_alter_table('ecosystem_contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecosystem_contributors_project_id'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_contributors_person_id'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_contributors_id'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_contributors_github_handle'))

    op.drop_table('ecosystem_contributors')
    with op.batch_alter_table('design_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_design_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_design_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_design_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_design_tasks_content_id'))
        batch_op.drop_index(batch_op.f('ix_design_tasks_community_id'))
        batch_op.drop_index(batch_op.f('ix_design_tasks_assignee_id'))

    op.drop_table('design_tasks')
    with op.batch_alter_table('content_communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_communities_content_id'))
        batch_op.drop_index(batch_op.f('ix_content_communities_community_id'))

    op.drop_table('content_communities')
    op.drop_table('content_collaborators')
    with op.batch_alter_table('content_assignees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_assignees_user_id'))
        batch_op.drop_index(batch_op.f('ix_content_assignees_content_id'))

    op.drop_table('content_assignees')
    op.drop_table('content_assets')
    with op.batch_alter_table('community_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_roles_person_id'))
        batch_op.drop_index(batch_op.f('ix_community_roles_id'))

    op.drop_table('community_roles')
    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_members_person_id'))
        batch_op.drop_index(batch_op.f('ix_committee_members_id'))
        batch_op.drop_index(batch_op.f('ix_committee_members_email'))
        batch_op.drop_index(batch_op.f('ix_committee_members_committee_id'))

    op.drop_table('committee_members')
    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_template_items_template_id'))

    op.drop_table('checklist_template_items')
    with op.batch_alter_table('campaign_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_tasks_campaign_id'))

    op.drop_table('campaign_tasks')
    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_contacts_person_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_contacts_campaign_id'))

    op.drop_table('campaign_contacts')
    with op.batch_alter_table('campaign_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_activities_person_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_activities_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_activities_campaign_id'))

    op.drop_table('campaign_activities')
    with op.batch_alter_table('wechat_stats_aggregates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wechat_stats_aggregates_period_type'))
        batch_op.drop_index(batch_op.f('ix_wechat_stats_aggregates_period_start'))
        batch_op.drop_index(batch_op.f('ix_wechat_stats_aggregates_id'))
        batch_op.drop_index(batch_op.f('ix_wechat_stats_aggregates_community_id'))
        batch_op.drop_index(batch_op.f('ix_wechat_stats_aggregates_article_category'))
        batch_op.drop_index('ix_aggregate_period')

    op.drop_table('wechat_stats_aggregates')
    with op.batch_alter_table('person_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_person_profiles_github_handle'))
        batch_op.drop_index(batch_op.f('ix_person_profiles_gitcode_handle'))
        batch_op.drop_index(batch_op.f('ix_person_profiles_email'))
        batch_op.drop_index(batch_op.f('ix_person_profiles_display_name'))
        batch_op.drop_index(batch_op.f('ix_person_profiles_company'))

    op.drop_table('person_profiles')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_templates_community_id'))

    op.drop_table('event_templates')
    with op.batch_alter_table('ecosystem_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecosystem_projects_id'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_projects_community_id'))

    op.drop_table('ecosystem_projects')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_work_status'))
        batch_op.drop_index(batch_op.f('ix_contents_scheduled_publish_at'))
        batch_op.drop_index(batch_op.f('ix_contents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contents_id'))
        batch_op.drop_index(batch_op.f('ix_contents_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_contents_community_id'))

    op.drop_table('contents')
    op.drop_table('community_users')
    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committees_id'))
        batch_op.drop_index(batch_op.f('ix_committees_community_id'))

    op.drop_table('committees')
    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_configs_id'))
        batch_op.drop_index(batch_op.f('ix_channel_configs_community_id'))

    op.drop_table('channel_configs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_community_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_community_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_id'))
        batch_op.drop_index(batch_op.f('ix_assets_community_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.drop_index(batch_op.f('ix_communities_name'))
        batch_op.drop_index(batch_op.f('ix_communities_id'))

    op.drop_table('communities')
    # ### end Alembic commands ###
